#!/bin/bash

#PBS -N JavierAcevedo27
#PBS -l nodes=1:ppn=8:intel
# PBS -l walltime=:5:00
#PBS -l mem=2gb
#PBS -M ja.acevedo12@uniandes.edu.co
#PBS -m ae
#PBS -j oe
#PBS -o out27.log

# cd $PBS_O_WORKDIR

pwd
cd ja.acevedo12/JavierAcevedo_Ejercicio27

module load gcc/4.9.4
make -f make123
#cp sample.pdf ..
# mkdir images
# mkdir datFiles

# mv -f $TMPDIR/CollisionalDarkMatterSimulation/images/ ./images
# mv -f $TMPDIR/CollisionalDarkMatterSimulation/datFiles/ ./datFiles





